const x = [
    'Sri Venkateswara Institute of Medical Sciences Andhra Pradesh',
    'Indian Institute of Information Technology, Sri City' ,
    'Indian Institute of Science Education and Research, Tirupati' ,
    'Indian Institute of Information Technology, Kurnool',
    'Indian Institute of Management Visakhapatnam',
    'National Institute of Technology, Andhra Pradesh',
    'National Institute of Design, Vijayawada',
    'Indian Institute of Technology Tirupati',
    'National Institute of Technology, Arunachal Pradesh',
    'Indian Institute of Technology, Guwahati',
    'National Institute of Design, Assam',
    'National Institute of Technology, Silchar',
    'National Institute of Technology, Patna',
    'Indian Institute of Information Technology, Bhagalpur',
    'Indian Institute of Technology, Patna',
    'Indian Institute of Management Bodh Gaya',
    'Indian Institute of Management Raipur',
    'Indian Institute of Technology Bhilai',
    'National Institute of Technology, Raipur',
    'Indian Institute of Technology, Delhi',
    'National Institute of Technology Delhi',
    'All India Institute of Medical Sciences, Delhi',
    'Indian Institute of Management, Ahmedabad',
    'Indian Institute of Technology Gandhinagar',
    'Sardar Vallabhbhai National Institute of Technology Surat',
    'Indian Institute of Management Rohtak',
    'National Institute of Technology Kurukshetra',
    'Indian Institute of Technology Mandi',
    'National Institute of Technology, Hamirpur',
    'Indian Institute of Management Sirmaur',
    'National Institute of Technology, Srinagar',
    'Indian Institute of Technology Jammu',
    'Indian Institute of Management Jammu',
    'Indian Institute of Technology (ISM), Dhanbad',
    'Indian Institute of Management Ranchi',
    'National Institute of Technology, Jamshedpur',
    'Indian Institute of Management Bangalore',
    'National Institute of Technology, Karnataka Surathkal',
    'Indian Institute of Technology, Dharwad',
    'Indian Institute of Technology Palakkad Palakkad',
    'Indian Institute of Management Kozhikode Kozhikode',
    'National Institute of Technology Calicut Kozhikode',
    'National Institute of Technology, Manipur',
    'Indian Institute of Management Indore',
    'Indian Institute of Technology Indore',
    'Indian Institute of Information Technology, Design and Manufacturing, Jabalpur',
    'Indian Institute of Information Technology and Management, Gwalior',
    'Maulana Azad National Institute of Technology, Bhopal',
    'All India Institute of Medical Sciences, Bhopal',
    'Indian Institute of Technology Bombay',
    'Visvesvaraya National Institute of Technology Nagpur',
    'Indian Institute of Management Nagpur',
    'Indian Institute of Management Shillong',
    'National Institute of Technology Meghalaya',
    'Indian Institute of Technology Bhubaneswar',
    'National Institute of Technology Rourkela',
    'Indian Institute of Management Sambalpur',
    'Dr. B R Ambedkar National Institute of Technology Jalandhar',
    'Indian Institute of Technology Ropar',
    'Indian Institute of Management Amritsar',
    'Indian Institute of Management Udaipur',
    'Indian Institute of Technology Jodhpur',
    'Malaviya National Institute of Technology Jaipur',
    'Indian Institute of Information Technology Design & Manufacturing Kancheepuram',
    'Indian Institute of Technology Madras',
    'Indian Institute of Management Tiruchirappalli',
    'National Institute of Technology, Tiruchirappalli',
    'Indian Institute of Technology Hyderabad',
    'National Institute of Technology, Warangal',
    'National Institute of Technology, Agartala',
    'Indian Institute of Management Lucknow',
    'Indian Institute of Technology Kanpur',
    'Indian Institute of Technology (Banaras Hindu University) Varanasi',
    'Indian Institute of Information Technology, Allahabad	',
    'Motilal Nehru National Institute of Technology	Allahabad',
    'Indian Institute of Management Kashipur',
    'Indian Institute of Technology Roorkee',
    'National Institute of Technology	Srinagar',
    'Indian Institute of Information Technology, Kalyani',
    'Indian Institute of Management Calcutta',
    'Indian Institute of Technology Kharagpur',
    'Indian Institute of Engineering Science and Technology, Shibpur',
    'National Institute of Technology, Durgapur',
];

const data = x.map(clg => ({
    label: clg,
    value:clg,
}));

const collegesData = (req, res) => {
    try {
        res.status(200).send(data);
    } catch (error) {
        res.status(400);
        throw new Error(error);
    }
    
}


module.exports = collegesData;

